# Generated by Django 3.1.5 on 2021-04-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rajyasainikboard',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zilasainikboard',
            name='code',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
