# Generated by Django 3.1.5 on 2021-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exservicemen',
            name='mobile',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
