# Generated by Django 3.1.5 on 2021-04-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentdetail',
            name='dep_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.civilqualification', verbose_name='Dependent Qualification'),
        ),
    ]
