# Generated by Django 3.1.5 on 2021-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydetail',
            name='basic_reg_type',
            field=models.CharField(choices=[('', '---------'), ('E', 'ESM'), ('W', 'Widow of already registered ESM'), ('TE', 'Transferred ESM/Widow'), ('UW', 'Widow of Unregistered/Died in service')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='esm_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='ppo_book',
            field=models.ImageField(blank=True, null=True, upload_to='images/ppo book', verbose_name='PPO BOOK'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EXSERVICEMEN'), (2, 'WELFARE_OFFICER'), (3, 'DIRECTOR'), (4, 'KSB'), (5, 'RSB'), (6, 'ADMIN')], default=1),
        ),
        migrations.AlterField(
            model_name='pensiondetail',
            name='ppo_no',
            field=models.CharField(max_length=8, verbose_name='PPO No'),
        ),
    ]
