# Generated by Django 3.1.5 on 2021-04-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenoprefix',
            name='esm_type',
        ),
        migrations.AddField(
            model_name='servicenoprefix',
            name='rank_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.rankcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicenoprefix',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.service'),
            preserve_default=False,
        ),
    ]
