# Generated by Django 3.1.5 on 2021-03-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='group',
            new_name='trade_group',
        ),
        migrations.RenameField(
            model_name='tradegroup',
            old_name='group',
            new_name='trade_group',
        ),
    ]
