# Generated by Django 3.1.5 on 2021-04-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210420_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentdetail',
            name='dep_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.civilqualification', verbose_name='Dependent Qualification'),
        ),
        migrations.AlterField(
            model_name='pensiondetail',
            name='ppo_no',
            field=models.CharField(blank=True, max_length=16, verbose_name='PPO No'),
        ),
    ]
