# Generated by Django 3.1.5 on 2021-04-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210419_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='civil_qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.civilqualification'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='corps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.corp'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.tradegroup'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.servicenoprefix'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='rank_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.rankcategory'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='record_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.recordoffice'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.exservicemen'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='reg_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.esmtype'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.service'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='service_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='suffix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.servicenosuffix'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.trade'),
        ),
        migrations.AddField(
            model_name='employmentdetail',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.specialization'),
            preserve_default=False,
        ),
    ]
