# Generated by Django 3.1.5 on 2021-03-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210314_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydetail',
            name='esm_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applydetail',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
