# Generated by Django 3.1.5 on 2021-04-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210420_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicedetail', to='exservicemen.exservicemen'),
        ),
    ]
