# Generated by Django 3.1.5 on 2021-04-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210420_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensiondetail',
            name='ppo_no',
            field=models.CharField(blank=True, max_length=16, verbose_name='PPO No'),
        ),
    ]
