# Generated by Django 3.1.5 on 2021-03-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0002_auto_20210304_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydetail',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
