# Generated by Django 3.1.5 on 2021-03-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0003_auto_20210322_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='bramch',
            new_name='zila_board',
        ),
        migrations.RenameField(
            model_name='welfareofficer',
            old_name='bramch',
            new_name='zila_board',
        ),
        migrations.RemoveField(
            model_name='ksbhead',
            name='bramch',
        ),
        migrations.RemoveField(
            model_name='ksbofficer',
            name='bramch',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='rsbhead',
            name='bramch',
        ),
        migrations.RemoveField(
            model_name='rsbofficer',
            name='bramch',
        ),
        migrations.AddField(
            model_name='exservicemen',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsbhead',
            name='rsb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.rajyasainikboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsbofficer',
            name='rsb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.rajyasainikboard'),
            preserve_default=False,
        ),
    ]
