# Generated by Django 3.1.5 on 2021-06-14 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0003_auto_20210421_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkUserEsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_Esm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exservicemen.exservicemen')),
                ('ref_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
