# Generated by Django 3.1.5 on 2021-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0003_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependentdetail',
            name='dep_no',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prefix',
            name='prefix',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='suffix',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
