# Generated by Django 3.1.5 on 2021-04-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0004_auto_20210404_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='record_office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.recordoffice'),
            preserve_default=False,
        ),
    ]
