# Generated by Django 3.1.5 on 2021-03-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0004_auto_20210322_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='decorations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='operations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='reg_date',
            field=models.DateField(),
        ),
    ]
