# Generated by Django 3.1.5 on 2021-06-19 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0004_linkuseresm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentdetail',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentdetail', to='exservicemen.exservicemen'),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employmentdetail', to='exservicemen.exservicemen'),
        ),
        migrations.AlterField(
            model_name='pensiondetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pensiondetail', to='exservicemen.exservicemen'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personaldetail', to='exservicemen.exservicemen'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spousedetail', to='exservicemen.exservicemen'),
        ),
    ]
