# Generated by Django 3.1.5 on 2021-06-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0005_auto_20210620_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESMDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esmdocument', to='exservicemen.exservicemen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_esm',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_user',
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='dep_relation',
            field=models.CharField(choices=[('', '---------'), ('W', 'WIFE'), ('S', 'SON'), ('D', 'DAUGHTER'), ('H', 'HUSBAND'), ('F', 'FATHER'), ('M', 'MOTHER')], default=None, max_length=1, verbose_name='Dependent Relation'),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='emp_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('E', 'EMPLOYED'), ('U', 'UUEMPLOYED')], max_length=1, null=True, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='marital_status',
            field=models.CharField(choices=[('', '---------'), ('U', 'UNMARRIED'), ('M', 'MARRIED')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='employment_status',
            field=models.CharField(choices=[('', '---------'), ('E', 'EMPLOYED'), ('U', 'UNEMPLOYED'), ('R', 'RETIRED')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='sector',
            field=models.CharField(blank=True, choices=[('C', 'CENTRAL GOVERNMENT'), ('S', 'STATE GOVERNMENT'), ('P', 'PRIVATE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(choices=[('', '---------'), ('M', 'MALE'), ('F', 'FEMALE')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='marital_status',
            field=models.CharField(choices=[('', '---------'), ('S', 'SINGLE'), ('M', 'MARRIED'), ('D', 'DIVORCED'), ('W', 'WIDOWER')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='spouse_employment_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('E', 'EMPLOYED'), ('U', 'UNEMPLOYED')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='spouse_relation',
            field=models.CharField(blank=True, choices=[('', '---------'), ('W', 'WIFE'), ('H', 'HUSBAND')], default=None, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='BasicDocument',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
