# Generated by Django 3.1.5 on 2021-04-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0005_corp_record_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spousedetail',
            name='marriage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
