# Generated by Django 3.1.5 on 2021-03-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0006_auto_20210322_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exservicemen',
            name='name',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='name',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widowdetail',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='is_address_same',
            field=models.CharField(choices=[('', '---------'), ('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
