# Generated by Django 3.1.5 on 2021-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0006_auto_20210404_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spousedetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
