# Generated by Django 3.1.5 on 2021-03-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0007_auto_20210323_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='mobile',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
