# Generated by Django 3.1.5 on 2021-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0007_auto_20210404_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='csd_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='CSD Number'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='echs_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ECHS Number'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ident_mark_1',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identification Mark 1'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='ident_mark_2',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identification Mark 2'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Permanent Account Number(PAN)'),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='voter_id_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Voter ID Number'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='aadhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='csd_no',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='CSD Number'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='echs_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='ECHS Number'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='ident_mark_1',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identification Mark 1'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='ident_mark_2',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Identification Mark 2'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Permanent Account Number(PAN)'),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='voter_id_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Voter ID Number'),
        ),
    ]
