# Generated by Django 3.1.5 on 2021-06-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0007_auto_20210624_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentaddress',
            name='ref',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='presentaddress', to='exservicemen.exservicemen'),
        ),
    ]
