# Generated by Django 3.1.5 on 2021-06-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0008_auto_20210628_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedetail',
            name='other_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='other_trade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
