# Generated by Django 3.1.5 on 2021-04-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0008_auto_20210404_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependentdetail',
            name='dep_no',
        ),
    ]
