# Generated by Django 3.1.5 on 2021-03-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0008_auto_20210323_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
