# Generated by Django 3.1.5 on 2021-04-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0009_remove_dependentdetail_dep_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prefix',
            name='suffix',
        ),
    ]
