# Generated by Django 3.1.5 on 2021-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0009_auto_20210323_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
