# Generated by Django 3.1.5 on 2021-06-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0009_auto_20210628_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='rank_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exservicemen.rankcategory'),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exservicemen.trade'),
        ),
    ]
