# Generated by Django 3.1.5 on 2021-06-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0010_auto_20210628_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permanentaddress',
            name='ref',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='permanentaddress', to='exservicemen.exservicemen'),
        ),
    ]
