# Generated by Django 3.1.5 on 2021-04-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0010_auto_20210412_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prefix',
            new_name='ServiceNoPrefix',
        ),
        migrations.RenameModel(
            old_name='Suffix',
            new_name='ServiceNoSuffix',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='prefix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.servicenoprefix'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='suffix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exservicemen.servicenosuffix'),
        ),
    ]
