# Generated by Django 3.1.5 on 2021-03-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0010_auto_20210323_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydetail',
            name='death_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/death_certificate'),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='is_address_same',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='corps',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exservicemen.corp'),
        ),
    ]
