# Generated by Django 3.1.5 on 2021-06-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0011_auto_20210628_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependentdetail',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='echs_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dependentdetail',
            name='voter_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='esmdocument',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='esmdocument',
            name='echs_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='esmdocument',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='esmdocument',
            name='voter_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='aadhaar_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='echs_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='pan_card',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='voter_id',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
