# Generated by Django 3.1.5 on 2021-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0011_auto_20210412_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensiondetail',
            name='ppo_no',
            field=models.CharField(blank=True, max_length=8, verbose_name='PPO No'),
        ),
    ]
