# Generated by Django 3.1.5 on 2021-03-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0011_auto_20210324_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=40)),
            ],
        ),
    ]
