# Generated by Django 3.1.5 on 2021-04-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0012_auto_20210413_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensiondetail',
            name='pension_sanctioned',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='pensiondetail',
            name='present_pension',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
