# Generated by Django 3.1.5 on 2021-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0013_auto_20210413_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exservicemen',
            name='reg_category',
            field=models.SmallIntegerField(choices=[(1, 'ESM'), (2, 'WIDOW'), (3, 'WIDOW IN SERVICE')]),
        ),
        migrations.DeleteModel(
            name='BasicRegType',
        ),
    ]
