# Generated by Django 3.1.5 on 2021-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0014_auto_20210413_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widowdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='widowdetail',
            name='whether_spouse_has_esm',
        ),
        migrations.AlterField(
            model_name='exservicemen',
            name='reg_category',
            field=models.SmallIntegerField(choices=[(1, 'ESM'), (2, 'WIDOW'), (3, 'WIDOW IN SERVICE / UNREGISTERED')]),
        ),
    ]
