# Generated by Django 3.1.5 on 2021-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0016_auto_20210414_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='dob',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='exservicemen',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'PENDING'), (3, 'EXPIRED'), (4, 'INCOMPLETE'), (5, 'UNDER QUERY')]),
        ),
        migrations.AlterField(
            model_name='spousedetail',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
    ]
