# Generated by Django 3.1.5 on 2021-04-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0017_auto_20210416_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='dob',
            field=models.DateField(default='2020-01-01', verbose_name='Date Of Birth'),
            preserve_default=False,
        ),
    ]
