# Generated by Django 3.1.5 on 2021-04-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exservicemen', '0018_auto_20210416_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='mobile',
        ),
        migrations.AddField(
            model_name='exservicemen',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
