from django.urls import path
from . import views

urlpatterns = [
    path('', views.homeview, name='home'),
    # path('apply/', views.applyview, name="apply"),
    # path('registration/', views.serviceformview, name="service details"),
    path('crud/', views.crud, name='crud'),
    path('crud/ajax/load_esm_list', views.load_esm_list, name='crud'),
    path('crud/update-esm/', views.update_esm, name='update esm'),
    path('registration/pension-info', views.pensionformview, name="pension details"),
    path('registration/personal-info', views.personalformview, name="personal details"),
    path('registration/employment-info', views.employmentformview, name='employment details'),
    path('registration/spouse-info', views.spouseformview, name='spouse details'),
    path('registration/dependent-info', views.dependentformview, name='dependent details'),
    path('registration/contact-info', views.contactformview, name='contact details'),
    path('user-login/', views.userlogin, name="user login"),
    path('officer-login/', views.officerlogin, name="officer login"),
    path('ajax/load-record-office/', views.load_record_office, name='ajax_load_records'),
    path('ajax/load-trades/', views.load_trades, name='ajax_load_trades'),
    path('ajax/load-ranks/', views.load_ranks, name='ajax_load_ranks'),
    path('ajax/load-prefixes/', views.load_prefixes, name='ajax_load_prefixes'),
    path('ajax/load-army-records/', views.load_army_records, name='ajax_army_records'),
    path('ajax/load-disrticts/', views.load_districts, name='ajax_load_districts'),
    path('registration/ajax/load_dependent/', views.load_dependent, name='ajax_load_dependent'),
    path('registration/ajax/add_dependent/', views.add_dependent, name='ajax_add_dependent'),
    path('registration/ajax/update_dependent/<int:pk>', views.update_dependent, name='ajax_update_dependent'),
    path('registration/ajax/delete_dependent/<int:pk>', views.delete_dependent, name='ajax_delete_dependent'),
    # path('ajax/load-mcs/', views.load_mcs, name='ajax_load_mcs'),
    path('logout/', views.userlogout, name='logout'),
    path('addesm/pending/<str:pk>', views.addesm, name='add ESM'),
    path('addesm/', views.addbasicinfo, name='basic details'),
    path('addesm/service-info', views.serviceformview, name='service details'),
    path('addesm/widow-info', views.widowformview, name='widow details'),
    path('addesm/submit', views.submit, name='submit form'),
]